server:
  port: 550

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/langrensha
    username: lrsAdmin
    password: lovelangrensha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
